<!-- SCRIPTS -->
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<!-- END SCRIPTS -->

<div class="container-fluid">
    <h3>ReCaptcha</h3>
    <form action="../../../ReCaptcha/CheckReCaptcha" method="post">
        <div class="row">
            <div class="form-group">
                <div class="col-sm-offset col-sm-12">
                    <div class="g-recaptcha" data-sitekey="6LdPQTIUAAAAABCjtqKqX4sXlj9PHPvPDIOOMh34" name="g-recaptcha-response"></div>
                </div>
            </div>
        </div>
        <hr />
        <div class="row">
    	    <div class="form-group">        
                <div class="col-sm-offset col-sm-12">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
</div>
    