<div class="container">
    <h3>Formulário Login</h3>
    
    <form action="/Login/Cadastro" method="POST"> 
        <div class="row">
        <div class="form-group">
            <label class="control-label col-sm-2" for="login">Nome:</label>
            <div class="col-sm-12">
                <input type="text" class="form-control" placeholder="Seu nome" name="nome">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="senha">Senha:</label>
            <div class="col-sm-12">          
                <input type="password" class="form-control" id="pwd" placeholder="Sua senha" name="senha">
            </div>
        </div>
        <div class="form-group">        
            <div class="col-sm-offset col-sm-12">
                <div class="checkbox">
                    <label><input type="checkbox" name="lembrar"> Lembrar-me</label>
                </div>
            </div>
        </div>
        </div>
        <hr />

        <div class="form-group">        
            <div class="col-sm-offset col-sm-12">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
</div>  

