     
<!-- SCRIPTS -->

<script type='text/javascript' src='../../Js/jQuery.js'></script>
<script type='text/javascript' src='../../Js/ConsultarCep.js'></script>

<!-- END SCRIPTS -->        

<div class="container-fluid">

    <h3 class="page-header">Cadastro de Fornecedor</h3>
  
    <form action="../Cadastro/Cadastra_Fornecedor" method="POST">
        <div class="row">
  	        <div class="form-group col-md-4">
  	  	        <label for="exampleInputEmail1">Nome / Razão Social</label>
  	  	        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Digite o valor">
              </div>
        </div>
        <div class="row">
            <div class="form-group col-md-4">
          	  	<label for="exampleInputEmail1">CEP</label>
  	  	        <input type="text" class="form-control" name="cep" id="cep" placeholder="Somente Números - Ex: 36016440">
            </div>
        </div>
        <div class="row">
	        <div class="form-group col-md-4">
      	  	    <label for="exampleInputEmail1">Cidade</label>
  	      	    <input type="text" class="form-control" name="cidade" id="cidade" placeholder="Digite o valor">
  	        </div>
	        <div class="form-group col-md-4">
          	  	<label for="exampleInputEmail1">Bairro</label>
  	  	        <input type="text" class="form-control" name="bairro" id="bairro" placeholder="Digite o valor">
            </div>
            <div class="form-group col-md-4">
          	  	<label for="exampleInputEmail1">Estado</label>
  	  	        <input type="text" class="form-control" name="estado" id="estado" placeholder="Digite o valor">
            </div>
            <div class="form-group col-md-4">
      	  	    <label for="exampleInputEmail1">Endereço</label>
  	  	        <input type="text" class="form-control" name="rua" id="rua" placeholder="Digite o valor">
            </div>
            <div class="form-group col-md-2">
      	  	    <label for="exampleInputEmail1">Número</label>
  	  	        <input type="text" class="form-control" name="numero" id="numero" placeholder="Digite o valor">
            </div>
            <div class="form-group col-md-2">
      	  	    <label for="exampleInputEmail1">Complemento</label>
  	  	        <input type="text" class="form-control" name="complemento" id="complemento" placeholder="Digite o valor">
  	        </div>
        </div>
	
        <div class="row">
  	        
	        <div class="form-group col-md-3">
          	  	<label for="exampleInputEmail1">Telefone 1</label>
  	      	    <input type="text" class="form-control" name="telefone1" id="telefone1" placeholder="Digite o valor">
  	        </div>
	        <div class="form-group col-md-3">
      	  	    <label for="exampleInputEmail1">Telefone 2</label>
  	  	        <input type="text" class="form-control" name="telefone2" id="telefone2" placeholder="Digite o valor">
  	        </div>	        
	    </div>
	
	<hr />
	
	    <div class="row">
    	    <div class="form-group">        
                <div class="col-sm-offset col-sm-12">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </div>
	    </div>

    </form>
 </div>
