<div class="container">
    <h3>URL</h3>
    
    <form action="../../Crawler/obter_links" method="POST"> 
    
        <div class="form-group">
            <label class="control-label col-sm-2" for="login">URL:</label>
            <div class="col-sm-12">
                <input type="text" class="form-control" placeholder="Url:" name="url">
            </div>
        </div>        
        <div class="form-group">        
            <div class="col-sm-offset col-sm-12">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
</div>  

